name: Discover active comp IDs (daily)

on:
  workflow_dispatch:
  schedule:
    - cron: "12 0 * * *"  # daily at 00:12 UTC

permissions:
  contents: write

jobs:
  discover:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # we'll base the worktree on origin/data if it exists

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python deps (selenium + bs4)
        run: |
          python -m pip install --upgrade pip
          pip install selenium beautifulsoup4

      # Chrome + matching ChromeDriver
      - id: setup-chrome
        uses: browser-actions/setup-chrome@v2
        with:
          chrome-version: stable
          install-dependencies: true
          install-chromedriver: true

      - name: Export CHROME_BIN
        run: echo "CHROME_BIN=${{ steps.setup-chrome.outputs.chrome-path }}" >> $GITHUB_ENV

      - name: Run discoverer (headless)
        run: |
          mkdir -p server/data
          python scraper/discover_active_compids.py \
            --range "1-150,450,650" --skip "72,73,108,114" \
            --out server/data/active_comp_ids.json -v

      # ✅ Publish ONLY active_comp_ids.json via a separate worktree (no branch switching in-place)
      - name: Publish active_comp_ids.json to data branch
        run: |
          set -e
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git fetch origin data || true

          # Create/update a detached worktree rooted on origin/data (or new branch if missing)
          WT_DIR="$(mktemp -d)"
          if git rev-parse --verify origin/data >/dev/null 2>&1; then
            git worktree add -B data "$WT_DIR" origin/data
          else
            # First-time creation of data branch from current HEAD
            git worktree add -B data "$WT_DIR"
          fi

          mkdir -p "$WT_DIR/server/data"
          cp -f server/data/active_comp_ids.json "$WT_DIR/server/data/active_comp_ids.json"

          cd "$WT_DIR"
          git add -f server/data/active_comp_ids.json
          git commit -m "discover: active comp IDs $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || echo "No changes"
          git push origin data

          # Clean up the worktree
          cd -
          git worktree remove "$WT_DIR" --force
